changelog:
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: Documentation
      labels:
        - docs
        - documentation
    - title: Maintenance
      labels:
        - chore
        - ci
        - refactor
        - release
    - title: Other Changes
      labels:
        - "*"
  exclude:
    labels:
      - skip-changelog
