import sys
import unittest
from pathlib import Path
from typing import List
from typing import Optional

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from nic.cli import build_parser
from nic.cli import derive_subnet
from nic.cli import interface_details
from nic.cli import normalize_netmask
from nic.cli import parse_collect_result
from nic.cli import parse_default_route
from nic.cli import parse_getmac_csv
from nic.cli import parse_ifconfig
from nic.cli import parse_ip_addr_json
from nic.cli import parse_ip_addr_output
from nic.cli import parse_ip_route_json
from nic.cli import parse_ip_route_output
from nic.cli import parse_ipconfig_all
from nic.cli import parse_linux_resolv_conf
from nic.cli import parse_route_print
from nic.cli import parse_system_profiler
from nic.cli import raw_command
from nic.cli import render_detail
from nic.cli import render_interface
from nic.cli import render_summary
from nic.cli import summary_group
from nic.cli import summary_visible


IFCONFIG_SAMPLE = """\
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
\toptions=6460<TSO4,TSO6,CHANNEL_IO,PARTIAL_CSUM,ZEROINVERT_CSUM>
\tether 5a:41:83:8a:50:40
\tinet6 fe80::1030:576d:44ef:5882%en0 prefixlen 64 secured scopeid 0xf
\tinet 172.17.6.246 netmask 0xfffffe00 broadcast 172.17.7.255
\tstatus: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
\tinet 127.0.0.1 netmask 0xff000000
\tinet6 ::1 prefixlen 128
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
\tinet6 fe80::412e:8b14:21e6:c3e4%utun0 prefixlen 64 scopeid 0x13
"""


DEFAULT_ROUTE_SAMPLE = """\
Routing tables

Internet:
Destination        Gateway            Flags               Netif Expire
default            172.17.6.1         UGScg                 en0
"""


SYSTEM_PROFILER_SAMPLE = """\
{
  "SPNetworkDataType" : [
    {
      "_name" : "Wi-Fi",
      "type" : "AirPort",
      "interface" : "en0",
      "Ethernet" : {
        "MAC Address" : "bc:d0:74:37:9b:99"
      },
      "DNS" : {
        "ServerAddresses" : ["223.5.5.5", "119.29.29.29"]
      },
      "IPv4" : {
        "Router" : "172.17.6.1"
      }
    }
  ]
}
"""


LINUX_IP_ADDR_JSON = """\
[
  {
    "ifname": "lo",
    "flags": ["LOOPBACK", "UP", "LOWER_UP"],
    "operstate": "UNKNOWN",
    "link_type": "loopback",
    "address": "00:00:00:00:00:00",
    "addr_info": [
      {"family": "inet", "local": "127.0.0.1", "prefixlen": 8},
      {"family": "inet6", "local": "::1", "prefixlen": 128}
    ]
  },
  {
    "ifname": "enp0s31f6",
    "flags": ["BROADCAST", "MULTICAST", "UP", "LOWER_UP"],
    "operstate": "UP",
    "link_type": "ether",
    "address": "52:54:00:12:34:56",
    "addr_info": [
      {"family": "inet", "local": "192.168.122.10", "prefixlen": 24},
      {"family": "inet6", "local": "fe80::5054:ff:fe12:3456", "prefixlen": 64}
    ]
  },
  {
    "ifname": "docker0",
    "flags": ["NO-CARRIER", "BROADCAST", "MULTICAST", "UP"],
    "operstate": "DOWN",
    "link_type": "ether",
    "address": "02:42:35:62:22:f8",
    "addr_info": [
      {"family": "inet", "local": "172.17.0.1", "prefixlen": 16}
    ]
  },
  {
    "ifname": "wg0",
    "flags": ["POINTOPOINT", "NOARP", "UP", "LOWER_UP"],
    "operstate": "UP",
    "link_type": "none",
    "address": "",
    "addr_info": [
      {"family": "inet", "local": "10.8.0.2", "prefixlen": 24}
    ]
  },
  {
    "ifname": "veth1234@if5",
    "flags": ["BROADCAST", "MULTICAST", "UP", "LOWER_UP"],
    "operstate": "UP",
    "link_type": "ether",
    "address": "4a:00:00:00:00:01",
    "addr_info": []
  }
]
"""


LINUX_IP_ADDR_TEXT = """\
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
    inet6 ::1/128 scope host
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP group default
    link/ether 52:54:00:12:34:56 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
    inet6 fe80::5054:ff:fe12:3456/64 scope link
3: wg0@if4: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 state UNKNOWN group default
    inet 10.8.0.2/24 scope global wg0
"""


LINUX_ROUTE_JSON = """\
[
  {
    "dst": "default",
    "gateway": "192.168.122.1",
    "dev": "enp0s31f6"
  }
]
"""


LINUX_ROUTE_TEXT = """\
default via 10.0.2.2 dev eth0 proto dhcp metric 100
10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.15 metric 100
"""


LINUX_RESOLV_CONF = """\
# generated by NetworkManager
nameserver 1.1.1.1
nameserver 8.8.8.8
"""


WINDOWS_IPCONFIG_SAMPLE = """\
Windows IP Configuration

Ethernet adapter Ethernet:
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Intel(R) Ethernet Connection
   Physical Address. . . . . . . . . : AA-BB-CC-DD-EE-FF
   DHCP Enabled. . . . . . . . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 192.168.1.25(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.1.1
   DNS Servers . . . . . . . . . . . : 1.1.1.1
                                       8.8.8.8

Wireless LAN adapter Wi-Fi:
   Media State . . . . . . . . . . . : Media disconnected
   Description . . . . . . . . . . . : Intel(R) Wi-Fi 6 AX200 160MHz
   Physical Address. . . . . . . . . : 11-22-33-44-55-66

Tunnel adapter WSL:
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : WSL (Hyper-V firewall)
   IPv6 Address. . . . . . . . . . . : fd00::1234(Preferred)
   Default Gateway . . . . . . . . . :
"""


WINDOWS_ROUTE_PRINT_SAMPLE = """\
===========================================================================
Interface List
 13...aa bb cc dd ee ff ......Intel(R) Ethernet Connection
===========================================================================
IPv4 Route Table
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0       192.168.1.1    192.168.1.25     25
Persistent Routes:
  None
"""


WINDOWS_GETMAC_SAMPLE = """\
"Ethernet","Intel(R) Ethernet Connection","AA-BB-CC-DD-EE-FF","\\Device\\Tcpip_{11111111-1111-1111-1111-111111111111}"
"Wi-Fi","Intel(R) Wi-Fi 6 AX200 160MHz","11-22-33-44-55-66","\\Device\\Tcpip_{22222222-2222-2222-2222-222222222222}"
"""


def sample_row(
    iface: str,
    type_: str,
    state: str,
    ipv4: str,
    current_mac: str,
    *,
    subnet: str = "",
    primary: bool = False,
    gateway: str = "",
    dns: Optional[List[str]] = None,
    ipv6: str = "-",
    hardware_mac: Optional[str] = None,
    family: str = "",
) -> dict:
    return {
        "iface": iface,
        "label": iface,
        "type": type_,
        "family": family,
        "state": state,
        "primary": primary,
        "ipv4": ipv4,
        "ipv4_item": None,
        "ipv6": ipv6,
        "current_mac": current_mac,
        "hardware_mac": hardware_mac or current_mac,
        "gateway": gateway,
        "dns": dns or [],
        "netmask": "",
        "subnet": subnet,
        "private_mac": False,
    }


def sample_data() -> dict:
    primary = sample_row(
        "en0",
        "Wi-Fi",
        "active",
        "172.17.6.246/23",
        "5a:41:83:8a:50:40",
        subnet="172.17.6.0/23",
        primary=True,
        gateway="172.17.6.1",
        dns=["223.5.5.5", "119.29.29.29"],
        ipv6="fe80::1030:576d:44ef:5882%en0/64",
        hardware_mac="bc:d0:74:37:9b:99",
        family="physical",
    )
    return {
        "default_route": {"gateway": "172.17.6.1", "interface": "en0"},
        "primary": primary,
        "physical": [
            primary,
            sample_row("en7", "Ethernet", "down", "-", "18:65:90:ab:cd:ef", family="physical"),
        ],
        "system": [
            sample_row(
                "bridge100",
                "Bridge",
                "active",
                "10.211.55.2/24",
                "be:d0:74:73:20:64",
                subnet="10.211.55.0/24",
                family="virtual",
            ),
            sample_row("vmenet1", "VM network", "active", "-", "ce:8a:fb:1c:07:34", family="virtual"),
            sample_row("awdl0", "AirDrop/Continuity", "active", "-", "92:00:00:00:00:01", family="system"),
        ],
        "tunnels": [
            sample_row(
                "utun4",
                "Tunnel/VPN",
                "active",
                "198.18.0.1/30",
                "-",
                subnet="198.18.0.0/30",
                family="tunnel",
            ),
            sample_row("utun5", "Tunnel/VPN", "active", "-", "-", family="tunnel"),
        ],
    }


class CliParsingTests(unittest.TestCase):
    def test_normalize_netmask_from_hex(self):
        dotted, prefix = normalize_netmask("0xfffffe00")
        self.assertEqual(dotted, "255.255.254.0")
        self.assertEqual(prefix, "23")

    def test_parse_ifconfig_extracts_mac_and_ipv4(self):
        interfaces = parse_ifconfig(IFCONFIG_SAMPLE)
        self.assertIn("en0", interfaces)
        self.assertEqual(interfaces["en0"]["mac"], "5a:41:83:8a:50:40")
        self.assertEqual(interfaces["en0"]["status"], "active")
        self.assertEqual(interfaces["en0"]["ipv4"][0]["address"], "172.17.6.246")

    def test_parse_default_route(self):
        route = parse_default_route(DEFAULT_ROUTE_SAMPLE)
        self.assertEqual(route["interface"], "en0")
        self.assertEqual(route["gateway"], "172.17.6.1")

    def test_parse_system_profiler(self):
        metadata = parse_system_profiler(SYSTEM_PROFILER_SAMPLE)
        self.assertEqual(metadata["en0"]["kind"], "Wi-Fi")
        self.assertEqual(metadata["en0"]["hardware_mac"], "bc:d0:74:37:9b:99")
        self.assertEqual(metadata["en0"]["dns"], ["223.5.5.5", "119.29.29.29"])

    def test_parse_ip_addr_json_extracts_linux_interfaces(self):
        interfaces = parse_ip_addr_json(LINUX_IP_ADDR_JSON)
        self.assertIn("enp0s31f6", interfaces)
        self.assertEqual(interfaces["enp0s31f6"]["mac"], "52:54:00:12:34:56")
        self.assertEqual(interfaces["enp0s31f6"]["ipv4"][0]["address"], "192.168.122.10")
        self.assertIn("veth1234", interfaces)

    def test_parse_ip_addr_output_fallback_extracts_linux_interfaces(self):
        interfaces = parse_ip_addr_output(LINUX_IP_ADDR_TEXT)
        self.assertEqual(interfaces["eth0"]["ipv4"][0]["prefix"], "24")
        self.assertEqual(interfaces["wg0"]["ipv4"][0]["address"], "10.8.0.2")

    def test_parse_ip_route_json(self):
        route = parse_ip_route_json(LINUX_ROUTE_JSON)
        self.assertEqual(route["interface"], "enp0s31f6")
        self.assertEqual(route["gateway"], "192.168.122.1")

    def test_parse_ip_route_output_fallback(self):
        route = parse_ip_route_output(LINUX_ROUTE_TEXT)
        self.assertEqual(route["interface"], "eth0")
        self.assertEqual(route["gateway"], "10.0.2.2")

    def test_parse_linux_resolv_conf(self):
        dns = parse_linux_resolv_conf(LINUX_RESOLV_CONF)
        self.assertEqual(dns, ["1.1.1.1", "8.8.8.8"])

    def test_parse_ipconfig_all_extracts_windows_interfaces(self):
        interfaces, metadata = parse_ipconfig_all(WINDOWS_IPCONFIG_SAMPLE)
        self.assertIn("Ethernet", interfaces)
        self.assertEqual(interfaces["Ethernet"]["mac"], "aa:bb:cc:dd:ee:ff")
        self.assertEqual(interfaces["Ethernet"]["ipv4"][0]["address"], "192.168.1.25")
        self.assertEqual(metadata["Ethernet"]["dns"], ["1.1.1.1", "8.8.8.8"])
        self.assertEqual(interfaces["Wi-Fi"]["status"], "inactive")
        self.assertEqual(metadata["WSL"]["kind"], "VM network")

    def test_parse_route_print(self):
        route = parse_route_print(WINDOWS_ROUTE_PRINT_SAMPLE)
        self.assertEqual(route["gateway"], "192.168.1.1")
        self.assertEqual(route["interface_ip"], "192.168.1.25")

    def test_parse_getmac_csv(self):
        metadata = parse_getmac_csv(WINDOWS_GETMAC_SAMPLE)
        self.assertEqual(metadata["Ethernet"]["hardware_mac"], "aa:bb:cc:dd:ee:ff")
        self.assertEqual(metadata["Wi-Fi"]["label"], "Intel(R) Wi-Fi 6 AX200 160MHz")

    def test_derive_subnet(self):
        subnet = derive_subnet(
            {
                "address": "172.17.6.246",
                "netmask": "255.255.254.0",
                "prefix": "23",
            }
        )
        self.assertEqual(subnet, "172.17.6.0/23")

    def test_parse_collect_result_linux_normalizes_groups(self):
        interfaces = parse_ip_addr_json(LINUX_IP_ADDR_JSON)
        default_route = parse_ip_route_json(LINUX_ROUTE_JSON)
        metadata = {}
        for name, info in interfaces.items():
            metadata[name] = {
                "label": name,
                "kind": "",
                "dns": ["1.1.1.1", "8.8.8.8"] if name == default_route["interface"] else [],
                "gateway": default_route["gateway"] if name == default_route["interface"] else "",
                "hardware_mac": info.get("mac", ""),
                "type_label": "",
            }
        data = parse_collect_result(interfaces, metadata, default_route)
        self.assertEqual(data["primary"]["iface"], "enp0s31f6")
        self.assertEqual(len(data["physical"]), 1)
        self.assertEqual(len(data["tunnels"]), 1)
        self.assertTrue(any(row["iface"] == "docker0" for row in data["system"]))
        self.assertTrue(any(row["iface"] == "veth1234" for row in data["system"]))

    def test_parse_collect_result_windows_maps_primary_and_subnet(self):
        interfaces, metadata = parse_ipconfig_all(WINDOWS_IPCONFIG_SAMPLE)
        route_info = parse_route_print(WINDOWS_ROUTE_PRINT_SAMPLE)
        default_route = {"gateway": route_info["gateway"], "interface": "Ethernet"}
        data = parse_collect_result(interfaces, metadata, default_route)
        self.assertEqual(data["primary"]["iface"], "Ethernet")
        ethernet = next(row for row in data["physical"] if row["iface"] == "Ethernet")
        self.assertEqual(ethernet["subnet"], "192.168.1.0/24")
        self.assertEqual(ethernet["dns"], ["1.1.1.1", "8.8.8.8"])

    def test_summary_visible_shows_vm_networks(self):
        self.assertTrue(
            summary_visible(
                {
                    "iface": "vmenet1",
                    "type": "VM network",
                    "family": "virtual",
                    "state": "active",
                    "ipv4": "-",
                    "primary": False,
                }
            )
        )

    def test_summary_visible_hides_helper_interfaces(self):
        self.assertFalse(
            summary_visible(
                {
                    "iface": "awdl0",
                    "type": "AirDrop/Continuity",
                    "family": "system",
                    "state": "active",
                    "ipv4": "-",
                    "primary": False,
                }
            )
        )

    def test_summary_visible_hides_container_veth(self):
        self.assertFalse(
            summary_visible(
                {
                    "iface": "veth1234",
                    "type": "Container veth",
                    "family": "system",
                    "state": "active",
                    "ipv4": "-",
                    "primary": False,
                }
            )
        )

    def test_summary_group_classifies_physical(self):
        self.assertEqual(
            summary_group(
                {
                    "iface": "en0",
                    "type": "Wi-Fi",
                    "family": "physical",
                    "state": "active",
                    "ipv4": "172.17.6.246/23",
                    "primary": True,
                }
            ),
            ("physical", "Physical / Host", "physical"),
        )

    def test_parse_collect_result_keeps_lan_label_as_physical(self):
        interfaces = {
            "en6": {
                "name": "en6",
                "header": "UP",
                "status": "",
                "mac": "00:e0:4c:82:5a:b3",
                "ipv4": [{"address": "192.168.50.10", "netmask": "255.255.255.0", "prefix": "24"}],
                "ipv6": [],
            }
        }
        metadata = {
            "en6": {
                "label": "USB 10/100/1000 LAN",
                "kind": "Ethernet",
                "dns": [],
                "gateway": "",
                "hardware_mac": "00:e0:4c:82:5a:b3",
                "type_label": "USB 10/100/1000 LAN",
            }
        }
        data = parse_collect_result(interfaces, metadata, {"gateway": "", "interface": ""})
        self.assertEqual(len(data["physical"]), 1)
        self.assertEqual(data["physical"][0]["type"], "USB 10/100/1000 LAN")

    def test_summary_group_classifies_virtual(self):
        self.assertEqual(
            summary_group(
                {
                    "iface": "bridge100",
                    "type": "Bridge",
                    "family": "virtual",
                    "state": "active",
                    "ipv4": "10.211.55.2/24",
                    "primary": False,
                }
            ),
            ("virtual", "VM / Virtual", "vm/virtual"),
        )

    def test_summary_group_classifies_vmenet_as_virtual(self):
        self.assertEqual(
            summary_group(
                {
                    "iface": "vmenet1",
                    "type": "System",
                    "family": "virtual",
                    "state": "active",
                    "ipv4": "-",
                    "primary": False,
                }
            ),
            ("virtual", "VM / Virtual", "vm/virtual"),
        )

    def test_summary_group_classifies_tunnel(self):
        self.assertEqual(
            summary_group(
                {
                    "iface": "wg0",
                    "type": "Tunnel/VPN",
                    "family": "tunnel",
                    "state": "active",
                    "ipv4": "10.8.0.2/24",
                    "primary": False,
                }
            ),
            ("tunnel", "Tunnel / VPN", "tunnel/VPN"),
        )

    def test_interface_details_skip_duplicate_hardware_mac(self):
        details = interface_details(
            {
                "iface": "bridge100",
                "type": "Bridge",
                "family": "virtual",
                "state": "active",
                "ipv4": "10.211.55.2/24",
                "subnet": "10.211.55.0/24",
                "netmask": "255.255.255.0",
                "gateway": "",
                "dns": [],
                "ipv6": "-",
                "current_mac": "be:d0:74:73:20:64",
                "hardware_mac": "be:d0:74:73:20:64",
                "private_mac": False,
            }
        )
        self.assertNotIn(("Hardware MAC", "be:d0:74:73:20:64"), details)

    def test_parser_accepts_detail_command(self):
        args = build_parser().parse_args(["detail"])
        self.assertEqual(args.command, "detail")

    def test_raw_command_dispatches_by_platform(self):
        self.assertEqual(raw_command("darwin"), ["ifconfig", "-a"])
        self.assertEqual(raw_command("linux"), ["ip", "addr"])
        self.assertEqual(raw_command("win32"), ["ipconfig", "/all"])

    def test_render_summary_is_compact_grouped_tables(self):
        output = render_summary(sample_data())
        self.assertIn("Physical / Host", output)
        self.assertIn("VM / Virtual", output)
        self.assertIn("Tunnel / VPN", output)
        self.assertIn("Subnet", output)
        self.assertIn("bridge100", output)
        self.assertIn("vmenet1", output)
        self.assertIn("172.17.6.0/23", output)
        self.assertNotIn("PRI", output)
        self.assertNotIn("STATE", output)
        self.assertNotIn("details", output)
        self.assertNotIn("Hidden        :", output)
        self.assertNotIn("awdl0", output)
        self.assertNotIn("utun5", output)

    def test_render_detail_keeps_verbose_interface_sections(self):
        output = render_detail(sample_data())
        self.assertIn("Hidden        :", output)
        self.assertIn("Active Physical / Host", output)
        self.assertIn("Physical / Host details", output)
        self.assertIn("Interface en0 (primary)", output)
        self.assertIn("PRI", output)
        self.assertIn("STATE", output)
        self.assertIn("Other physical adapters", output)

    def test_render_interface_still_returns_single_interface_detail(self):
        output = render_interface(sample_data(), "en0")
        self.assertIn("Interface en0", output)
        self.assertIn("Subnet", output)
        self.assertIn("Current MAC", output)


if __name__ == "__main__":
    unittest.main()
